### ISSUE TITLE
Update default branch to main

### ISSUE THREAD

**Issue by thomas-robinson** [earth-system-radiation/rte-ecckd#2]
Hello.  Would it be possible to update the default branch on this repo to `main`.  My organization has a fork of this repository and I am updating all of the default branches.  I don't want to make the update on my end until this repo is updated.

**Comment by RobertPincus** [comment]
@menzel-gfdl I don't mind to do this, any objections on your side?

**Comment by RobertPincus** [comment]
@thomas-robinson @menzel-gfdl Does it make sense for GFDL to maintain a separate fork? Any reason not to this repo directly?

**Comment by menzel-r** [comment]
@RobertPincus I made a fork because I changed the I/O and error handling to use FMS, but I don't think we want to do that in this repository.

**Comment by RobertPincus** [comment]
@thomas-robinson I've renamed the `master` branch to `main` as requested.
